In [1]:
import pickle

# Gdata.pickle 파일 열기
with open('Gdata.pickle', 'rb') as file:
    data = pickle.load(file)

# 데이터 내용 확인
print(data)


Data(x=[18628, 101], edge_index=[2, 421207], edge_weights=[421207])


In [2]:
import pickle

# Gdata.pickle 파일 열기
with open('Gdata.pickle', 'rb') as file:
    data = pickle.load(file)

# 각 데이터 구성 요소 출력
print("Node Features (x):", data.x)
print("Edge Index (edge_index):", data.edge_index)
print("Edge Weights (edge_weights):", data.edge_weights)


Node Features (x): tensor([[-1.6215e+00,  7.0836e+00,  9.8246e+00,  ...,  1.0975e-02,
          5.3116e-01,  8.7530e-01],
        [-2.7096e+00,  7.1661e+00,  5.0720e+00,  ..., -2.0568e-01,
          1.9162e-01, -1.1393e-01],
        [-3.0119e+00,  1.0507e+01, -6.6003e-01,  ...,  1.7014e-01,
          6.4177e-02,  6.7956e-01],
        ...,
        [ 1.1736e+01,  1.8279e+00, -6.2040e+00,  ...,  2.2609e-01,
         -4.0374e-02, -7.7253e-02],
        [ 1.2028e+01,  4.8045e-01, -6.5192e+00,  ..., -3.0304e-01,
          4.8986e-01,  1.3183e-01],
        [ 1.2483e+01,  7.9646e-02, -6.7985e+00,  ..., -1.8702e-01,
          2.9372e-01,  1.0492e-01]])
Edge Index (edge_index): tensor([[    0,     0,     0,  ..., 18625, 18626, 18627],
        [    0,     4,     5,  ..., 18626, 18626, 18627]])
Edge Weights (edge_weights): tensor([1.0000, 0.9995, 0.9998,  ..., 0.9997, 1.0000, 1.0000])


In [3]:
import pickle

# Gdata.pickle 파일 열기
with open('Gdata.pickle', 'rb') as file:
    data = pickle.load(file)

# 데이터 전체 출력
print("전체 데이터 출력:")
print(data)

# 노드 특성, 엣지 인덱스, 엣지 가중치 등 개별적으로 확인
print("\nNode Features (x):")
print(data.x)

print("\nEdge Index (edge_index):")
print(data.edge_index)

print("\nEdge Weights (edge_weights):")
print(data.edge_weights)


전체 데이터 출력:
Data(x=[18628, 101], edge_index=[2, 421207], edge_weights=[421207])

Node Features (x):
tensor([[-1.6215e+00,  7.0836e+00,  9.8246e+00,  ...,  1.0975e-02,
          5.3116e-01,  8.7530e-01],
        [-2.7096e+00,  7.1661e+00,  5.0720e+00,  ..., -2.0568e-01,
          1.9162e-01, -1.1393e-01],
        [-3.0119e+00,  1.0507e+01, -6.6003e-01,  ...,  1.7014e-01,
          6.4177e-02,  6.7956e-01],
        ...,
        [ 1.1736e+01,  1.8279e+00, -6.2040e+00,  ...,  2.2609e-01,
         -4.0374e-02, -7.7253e-02],
        [ 1.2028e+01,  4.8045e-01, -6.5192e+00,  ..., -3.0304e-01,
          4.8986e-01,  1.3183e-01],
        [ 1.2483e+01,  7.9646e-02, -6.7985e+00,  ..., -1.8702e-01,
          2.9372e-01,  1.0492e-01]])

Edge Index (edge_index):
tensor([[    0,     0,     0,  ..., 18625, 18626, 18627],
        [    0,     4,     5,  ..., 18626, 18626, 18627]])

Edge Weights (edge_weights):
tensor([1.0000, 0.9995, 0.9998,  ..., 0.9997, 1.0000, 1.0000])


In [4]:
from datasets import Dataset

# .arrow 파일이 저장된 경로
dataset_path = './cell_dt'

# Dataset 객체로 로드
dataset = Dataset.load_from_disk(dataset_path)

# 데이터 내용 확인
print(dataset)


Dataset({
    features: ['input_ids', 'cell_label'],
    num_rows: 326751
})


In [5]:
# 첫 번째 항목 보기
print(dataset[0])

# 데이터의 몇 가지 샘플 보기
for i in range(5):
    print(dataset[i])


{'input_ids': [1747, 10933, 6376, 7247, 3777, 2439, 16481, 12460, 4547, 4275, 8565, 1823, 3792, 331, 1319, 5855, 13257, 15470, 14299, 852, 3758, 16411, 11180, 5267, 2061, 5592, 1071, 4703, 17715, 5538, 16979, 8063, 19475, 12716, 4608, 10951, 556, 20613, 11483, 3942, 6122, 12530, 16830, 11654, 15506, 17236, 15581, 1007, 17224, 22562, 5212, 8674, 17314, 16910, 14930, 7773, 18537, 5908, 19925, 12699, 15507, 16792, 5368, 16913, 10374, 17326, 1129, 8454, 3739, 5785, 4088, 1803, 2359, 2109, 3717, 8964, 20320, 4827, 1984, 2992, 6594, 18754, 6652, 5647, 200, 5760, 11019, 6608, 16606, 16297, 10639, 6206, 6549, 6922, 16621, 7295, 3259, 8008, 8205, 4037, 7606, 8919, 8456, 3312, 9220, 7342, 3852, 14844, 1684, 15646, 4839, 8053, 5716, 8965, 9082, 1279, 6143, 17911, 1965, 11457, 4125, 5815, 8400, 3522, 3845, 5383, 2551, 12827, 16337, 8967, 8666, 12627, 3875, 3261, 14741, 8143, 7203, 12215, 11785, 11543, 2078, 7962, 1296, 4189, 76, 808, 3615, 4933, 16753, 2196, 10548, 3991, 16239, 1718, 13327, 14335,

In [6]:
# 데이터셋의 컬럼과 구조 확인
print(dataset.column_names)


['input_ids', 'cell_label']


In [8]:
from collections import Counter
from datasets import load_from_disk

# 데이터셋 로드
dataset = load_from_disk('./cell_dt')

# cell_label 값의 분포 확인
label_counts = Counter(dataset['cell_label'])
print(label_counts)


Counter({0: 163794, 1: 162957})


In [10]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


1.13.1+cu117
True


In [1]:
import torch
print(torch.__version__)  # PyTorch 버전 확인
print(torch.cuda.is_available())  # CUDA 가용성 확인

1.13.1
False


/data/project/eunyi/Anaconda3/envs/drugformer/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import torch
print(torch.__version__)  # PyTorch 버전 확인
print(torch.cuda.is_available())  # CUDA 사용 가능 여부 확인

1.13.1+cu117
True


In [1]:
import torch
print(torch.cuda.is_available())  # True이면 CUDA가 활성화된 상태
print(torch.cuda.current_device())  # 현재 사용 중인 GPU 장치 ID 확인
print(torch.cuda.get_device_name(0))  # 첫 번째 GPU 장치 이름 확인

True
0
NVIDIA RTX A5000


In [3]:
import torch_geometric
print(torch_geometric.__version__)

2.3.1


In [8]:
import pickle

# Gdata.pickle 파일 열기
with open('dictionary_genename_token_pair.pickle', 'rb') as file:
    data = pickle.load(file)

# 데이터 전체 출력
print("전체 데이터 출력:")
print(data)

# 데이터의 전체 길이 출력
print(f"데이터 길이: {len(data)}")

# 데이터의 일부 출력 (예: 처음 10개 항목만)
print("데이터 일부 출력:")
for key, value in list(data.items())[:15]:  # 처음 10개 항목만 출력
    print(f"{key}: {value}")

# ID 값의 범위 확인
values = list(data.values())
min_value = min(values)
max_value = max(values)
print(f"ID 값의 최소값: {min_value}")
print(f"ID 값의 최대값: {max_value}")

# 유전자 이름의 갯수 확인
num_genes = len(data)
print(f"총 유전자 및 특수 토큰의 갯수: {num_genes}")

전체 데이터 출력:
{'<pad>': 0, '<mask>': 1, 'A': 25426, 'G': 25427, 'C': 25428, 'T': 25429, '<cell_cls>': 25430, '<gene_cls>': 25431, '<hybrid_cls>': 25432, '<sep>': 25433, '<prompt_beg>': 25434, '<prompt_end>': 25435, 'TSPAN6': 2, 'TNMD': 3, 'DPM1': 4, 'SCYL3': 5, 'C1orf112': 6, 'FGR': 7, 'CFH': 8, 'FUCA2': 9, 'GCLC': 10, 'NFYA': 11, 'STPG1': 12, 'NIPAL3': 13, 'LAS1L': 14, 'ENPP4': 15, 'SEMA3F': 16, 'CFTR': 17, 'ANKIB1': 18, 'CYP51A1': 19, 'KRIT1': 20, 'RAD52': 21, 'BAD': 22, 'LAP3': 23, 'CD99': 24, 'HS3ST1': 25, 'AOC1': 26, 'WNT16': 27, 'HECW1': 28, 'MAD1L1': 29, 'LASP1': 30, 'SNX11': 31, 'TMEM176A': 32, 'M6PR': 33, 'KLHL13': 34, 'CYP26B1': 35, 'ICA1': 36, 'DBNDD1': 37, 'ALS2': 38, 'CASP10': 39, 'CFLAR': 40, 'TFPI': 41, 'NDUFAF7': 42, 'RBM5': 43, 'MTMR7': 44, 'SLC7A2': 45, 'ARF5': 46, 'SARM1': 47, 'POLDIP2': 48, 'PLXND1': 49, 'AK2': 50, 'CD38': 51, 'FKBP4': 52, 'KDM1A': 53, 'RBM6': 54, 'CAMKK1': 55, 'RECQL': 56, 'VPS50': 57, 'HSPB6': 58, 'ARHGAP33': 59, 'NDUFAB1': 60, 'PDK4': 61, 'SLC22A16'

In [1]:
import pandas as pd
txt = pd.read_csv("/data/project/eunyi/DrugFormer/original_data/GSE104987_mal_countsMatrix.txt", sep="\t")
txt

Cell_barcode  Condition  AAAS  AACS  AAED1  AAGAB  AAK1  AAMDC  \
0     C70R_C70R.bcDWVD  resistant     1     0      0      0     0      0   
1     C70R_C70R.bcFKNC  resistant     0     0      0      0     0      0   
2     C70R_C70R.bcATGT  resistant     0     0      0      0     0      0   
3     C70R_C70R.bcCPAD  resistant     0     0      0      0     0      0   
4     C70R_C70R.bcBIIV  resistant     0     1      0      0     0      0   
...                ...        ...   ...   ...    ...    ...   ...    ...   
2664  MCF7_MCF7.bcCZFC  sensitive     0     0      0      1     0      0   
2665  MCF7_MCF7.bcFMVY  sensitive     0     0      0      0     0      2   
2666  MCF7_MCF7.bcCFOT  sensitive     0     0      0      0     0      0   
2667  MCF7_MCF7.bcABES  sensitive     0     0      0      0     0      0   
2668  MCF7_MCF7.bcEEDY  sensitive     0     0      0      0     0      0   

      AAMP  AAR2  ...  ZNF740  ZNF761  ZNF776  ZNF786  ZNF827  ZNF830  ZNF844  \
0        0     0  ...       0       0       0       0       0       0       0   
1        2     0  ...       0       0       0       0       0       0       0   
2        0     0  ...       0       0       0       0       0       0       0   
3        0     0  ...       0       0       0       0       0       0       0   
4        0     0  ...       0       0       0       0       0       0       0   
...    ...   ...  ...     ...     ...     ...     ...     ...     ...     ...   
2664     0     0  ...       0       0       0       0       0       0       0   
2665     0     0  ...       0       0       0       0       0       0       0   
2666     1     0  ...       0       0       0       0       0       0       0   
2667     0     0  ...       0       0       0       0       0       0       0   
2668     0     0  ...       0       0       0       0       0       0       0   

      ZNHIT6  ZNRF3  ZSCAN18  
0          0      0        0  
1          0      0        0  
2          0      0        0  
3          0      0        0  
4          0      0        0  
...      ...    ...      ...  
2664       0      0        0  
2665       0      0        0  
2666       0      0        0  
2667       0      0        0  
2668       0      0        0  

[2669 rows x 8478 columns]

In [3]:
from datasets import load_from_disk

# 파일 경로 설정 (디렉토리 경로로 수정)
directory_path = "/data/project/eunyi/DrugFormer/cell_dt/"

# 데이터 로드
dataset = load_from_disk(directory_path)

# 데이터 확인
print(dataset)

Dataset({
    features: ['input_ids', 'cell_label'],
    num_rows: 326751
})


In [2]:
import pandas as pd

# 엑셀 파일 경로
file_path = '/data/project/eunyi/DrugFormer/DRMref_datasets_malignantCells_number_details.xlsx'

# 엑셀 파일 열기
data = pd.read_excel(file_path)

# 데이터 출력
print(data.head())

                       dataset_subgroup         Dataset Original_Dataset  \
0     GSE161801_PI_mal_pre_countsMatrix    GSE161801_PI        GSE161801   
1    GSE161801_PI_mal_post_countsMatrix    GSE161801_PI        GSE161801   
2   GSE161801_IMiD_mal_pre_countsMatrix  GSE161801_IMiD        GSE161801   
3  GSE161801_IMiD_mal_post_countsMatrix  GSE161801_IMiD        GSE161801   
4        GSE161195_mal_pre_countsMatrix       GSE161195        GSE161195   

   res_mal_n  sen_mal_n    Source                Tissue Cancer_type_level1  \
0        857        677  patients  Bone marrow aspirate   Multiple myeloma   
1       1638        254  patients  Bone marrow aspirate   Multiple myeloma   
2      10897       5140  patients  Bone marrow aspirate   Multiple myeloma   
3      10922       7929  patients  Bone marrow aspirate   Multiple myeloma   
4       7311      18116  patients  Bone marrow aspirate   Multiple myeloma   

                 Cancer_type_level2         Drug_type  ...      Organism  

In [3]:
# 파일 경로 설정
file_path = '/data/project/eunyi/DrugFormer/gene_summary.txt'

# 파일을 열어서 내용 읽기
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.readlines()

# 첫 5줄 출력
for line in content[:5]:
    print(line.strip())  # strip()을 사용하여 줄 끝의 공백 문자 제거

p_val	avg_log2FC	pct.1	pct.2	p_val_adj	Gene_symbol	Cell_type	dataset_subgroup	ensembl_gene_id	entrezgene_id	entrezgene_description	external_synonym	gene_biotype	uniprotswissprot	Dataset	Original_Dataset	Cancer_type_level1	Cancer_type_level2	Drug_type	Timepoint	Regimen	Organism	Source	Tissue	Sample_size	Sample_size_all	Cell_number_all	Date	PMID	Description	RawData_ID	Extract_protocol	Data_processing	Cancer_type_level1_forDB	Drug_type_forDB	primary_key
7.23013518335309e-287	1.57450241510378	0.977	0.696	5.57949532099358e-283	FTL	Malignant cells	GSE104987	ENSG00000087086	2512	ferritin light chain	MGC71996|NBIA3	protein_coding	P02792	GSE104987	GSE104987	Breast cancer	ER+ breast cancer	Targeted therapy	NA	KDM5-C70	Homo sapiens	MCF7 cell line	Cell line	resistant 1, sensitive 1	2	2669	Public on Oct 03, 2018	30472020	This dataset has 1 cell line with a sensitive pre-treatment sample and a resistant post-treatment sample.	PRJNA414337	inDrop v3	indrops pipeline	Breast_cancer	Targeted_therapy	1
7.

In [5]:
# 첫 번째 줄을 보기 좋게 줄바꿈 추가해서 출력
for line in content[:1]:
    print(line.strip().replace('\t', '\n'))  # 탭 구분을 줄바꿈으로 변경

p_val
avg_log2FC
pct.1
pct.2
p_val_adj
Gene_symbol
Cell_type
dataset_subgroup
ensembl_gene_id
entrezgene_id
entrezgene_description
external_synonym
gene_biotype
uniprotswissprot
Dataset
Original_Dataset
Cancer_type_level1
Cancer_type_level2
Drug_type
Timepoint
Regimen
Organism
Source
Tissue
Sample_size
Sample_size_all
Cell_number_all
Date
PMID
Description
RawData_ID
Extract_protocol
Data_processing
Cancer_type_level1_forDB
Drug_type_forDB
primary_key
